active_branch: Moilapp-V4.0
list_branch:
- Moilapp-V1.0
- Moilapp-V2.0
- Moilapp-V3.0
- Moilapp-V3.1
- Moilapp-V4.0
- develop
- develop_for_cj
- develop_v4.1
- main
origin_url: https://McutOIL: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@github.com/McutOIL/moilapp.git
token: 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
user_name: McutOIL
